# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brian McManus
email: me@brianmcmanus.org
description: >
  I'm a web developer currently living in San Francisco, CA. Ok, well not really
  San Francisco, more like Daly City cause who can afford that shit? I mostly
  use Ruby and Javascript with sprinkles of Elixir thrown in for good measure.
  I'm also a wannabe drummer. :notes:
author:
  gravatar_md5: 85e7f9ef6dbf544f2227aab1e5a85f04
  email: me@brianmcmanus.org
  links:
    - icon: github
      url: https://github.com/bdmac
    - icon: twitter
      url: https://twitter.com/bdmac97
    - icon: linkedin
      url: https://www.linkedin.com/in/bdmac
  twitter_username: bdmac97
  linkedin_username: bdmac
google_analytics: UA-89272810-1

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock